name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: windows
            arch: 386
            output: webserver-windows-386.exe

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      env:
        GOOS: ${{ matrix.os }}
        GOARCH: ${{ matrix.arch }}
      run: |
        go get
        go build -o ${{ matrix.output }} -v ./...
        ls -l
        
    - name: Keep artifacts if master branch
      # if: github.ref == 'refs/heads/master'
      uses: actions/upload-artifact@v2
      with:
        name: webserver-${{ matrix.os }}-${{ matrix.arch }}
        path: ${{ matrix.output }}
